"""add_ebpf_correction_fields

Revision ID: c2343e8e8bb0
Revises: 
Create Date: 2026-06-13 02:12:48.461079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2343e8e8bb0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vulnerability', sa.Column('llm_original_type', sa.String(length=100), nullable=True, comment='LLM初始分类(若被eBPF纠正则保留此字段)'))
    op.add_column('vulnerability', sa.Column('ebpf_corrected', sa.Boolean(), nullable=True, comment='是否被eBPF运行时证据纠正分类'))
    # 为已存在的数据设置默认值False
    op.execute("UPDATE vulnerability SET ebpf_corrected = false WHERE ebpf_corrected IS NULL")
    # 然后将列改为NOT NULL
    op.alter_column('vulnerability', 'ebpf_corrected', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vulnerability', 'ebpf_corrected')
    op.drop_column('vulnerability', 'llm_original_type')
    # ### end Alembic commands ###
